"""likes_system

Revision ID: 070b230b4b45
Revises: 38445f43fde0
Create Date: 2018-08-24 20:47:35.793393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070b230b4b45'
down_revision = '38445f43fde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channelsessionaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channel', sa.Column('likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'likes')
    op.drop_table('channelsessionaction')
    # ### end Alembic commands ###
