"""channel_lang_not_null

Revision ID: 10d3450af02
Revises: 576da1007e5
Create Date: 2018-08-24 19:07:08.563503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d3450af02'
down_revision = '576da1007e5'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'language',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'language',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
