"""fixing_migrations

Revision ID: 93fbce563c87
Revises: 1adf997157b1
Create Date: 2018-06-09 22:56:50.833086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93fbce563c87'
down_revision = '1adf997157b1'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('bot', 'title', existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column('bot', 'username', existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column('category', 'name', existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column('channel', 'description',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('channel', 'photo',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('channel', 'username',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_index('ix_channel_category_id', table_name='channel')
    op.drop_index('ix_channeladmin_admin_id', table_name='channeladmin')
    op.drop_index('ix_channeladmin_channel_id', table_name='channeladmin')
    op.drop_index('ix_channeltag_channel_id', table_name='channeltag')
    op.drop_index('ix_channeltag_tag_id', table_name='channeltag')
    op.alter_column('client', 'first_name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('client', 'language_code',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('session', 'expiration',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.drop_index('ix_session_client_id', table_name='session')
    op.alter_column('sticker', 'installs',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('sticker', 'title',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('sticker', 'username',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sticker', 'username',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('sticker', 'title',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('sticker', 'installs',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_index('ix_session_client_id', 'session', ['client_id'], unique=False)
    op.alter_column('session', 'expiration',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('client', 'language_code',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('client', 'first_name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.create_index('ix_channeltag_tag_id', 'channeltag', ['tag_id'], unique=False)
    op.create_index('ix_channeltag_channel_id', 'channeltag', ['channel_id'], unique=False)
    op.create_index('ix_channeladmin_channel_id', 'channeladmin', ['channel_id'], unique=False)
    op.create_index('ix_channeladmin_admin_id', 'channeladmin', ['admin_id'], unique=False)
    op.create_index('ix_channel_category_id', 'channel', ['category_id'], unique=False)
    op.alter_column('channel', 'username',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('channel', 'photo',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('channel', 'description',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('category', 'name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('bot', 'username',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('bot', 'title',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
