"""add_channel_mutual_promotion

Revision ID: a447a9bc59a2
Revises: 38445f43fde0
Create Date: 2018-08-23 22:36:46.143740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a447a9bc59a2'
down_revision = '38445f43fde0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channelsessionaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channel', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('channel', sa.Column('mutual_promotion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'mutual_promotion')
    op.drop_column('channel', 'likes')
    op.drop_table('channelsessionaction')
    # ### end Alembic commands ###
