"""channel_admin_revision

Revision ID: d88273467574
Revises: 0c224c621d0f
Create Date: 2018-09-04 00:35:14.320126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd88273467574'
down_revision = '0c224c621d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channeladmin', sa.Column('owner', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('channeladmin', sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channeladmin', 'raw')
    op.drop_column('channeladmin', 'owner')
    # ### end Alembic commands ###
